---
- name: Run backup management script
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    script_path: "./scripts/manage_backup.sh"

  tasks:
    - name: Ensure script is executable
      ansible.builtin.file:
        path: "{{ script_path }}"
        mode: '0755'

    - name: Run backup management script
      ansible.builtin.shell: "{{ script_path }}"
      register: script_output
      ignore_errors: no

    - name: Show script output
      ansible.builtin.debug:
        var: script_output.stdout
