---
- name: Run manage_backup.sh
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Execute script manage_backup.sh
      ansible.builtin.shell: ./scripts/manage_backup.sh
      args:
        chdir: "{{ playbook_dir }}"
