---
- name: Run manage_backup.sh
  hosts: localhost
  connection: local
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Verificar se manage_backup.sh existe
      ansible.builtin.stat:
        path: "{{ playbook_dir }}/scripts/manage_backup.sh"
      register: script_file

    - name: Falhar se o script não existir
      ansible.builtin.fail:
        msg: "Script manage_backup.sh não encontrado em {{ playbook_dir }}/scripts/"
      when: not script_file.stat.exists

    - name: Executar manage_backup.sh
      ansible.builtin.shell: ./manage_backup.sh
      args:
        chdir: "{{ playbook_dir }}/scripts"
      register: script_output
      when: script_file.stat.exists

    - name: Mostrar saída do script
      ansible.builtin.debug:
        var: script_output
